version: '3.7'

services:

  #########
  # Postgres

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  #########
  # Redis

  redis:
    container_name: redis
    image: library/redis
    expose:
      - "6379"

volumes:
  postgres-data:
    driver: local
